title: Gene Weaver
description: Automated Primer Design for Transcription Factor Research.
logo: /assets/img/Gene_Weaver.png 
url: "https://AileenCohen.github.io/Gene-Weaver" 
baseurl: "/GeneWeaver" 
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
